# This is a service gateway to the replica set created by the deployment.
# Take a look at the deployment.yaml for general notes about this chart.
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  ports:
  - port: {{default 6379 .Values.redisPort}}
    targetPort: cache
    protocol: TCP
    name: cache
  selector:
    app: redis
