# Default values for postgres.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image: postgres:9.5
pullPolicy: IfNotPresent

persistence:
  enabled: false

# env_vars:
#   DB_USER: gitlab
#   DB_PASS: gitlab
#   DB_NAME: gitlab_production
#   DB_EXTENSION: pg_trgm
