apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: result-app
  labels:
    # The "heritage" label is used to track which tool deployed a given chart.
    # It is useful for admins who want to see what releases a particular tool
    # is responsible for.
    heritage: {{ .Release.Service | quote }}
    # This makes it easy to search for all components of a release using kubectl.
    release: {{ .Release.Name | quote }}
    # This makes it easy to audit chart usage.
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: result-app
        release: {{.Release.Name | quote }}
    spec:
      containers:
      - name: result-app
        image: {{ .Values.image }}:{{ .Values.imageTag }}
        imagePullPolicy: {{default "IfNotPresent" .Values.pullPolicy}}
        ports:
        - containerPort: 80
          name: http
