# Default values for result-app.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image: willies/example-voting-app-result
imageTag: latest
# nodePort: 30051
